<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-03-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("author", models.CharField(max_length=20)),
                ("page_count", models.BigIntegerField()),
            ],
        ),
    ]
=======
# Generated by Django 5.0.2 on 2024-03-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("author", models.CharField(max_length=20)),
                ("page_count", models.BigIntegerField()),
            ],
        ),
    ]
>>>>>>> 1d221d9c65af698a7761a514f421d3a52566b2c1
